; Script generated by the Gemini CLI for TDitbam Streamer Suite
#define MyAppName "TDitbam Streamer Suite"
#define MyAppVersion "3.3.0"
#define MyAppPublisher "Tditbam"
#define MyAppURL "https://github.com/TDitbam/TDitbam-Streamer-Suite"
#define MyAppExeName "TDitbam-Streamer-Suite.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{D3D3A6A0-9E1D-4F1B-9D8F-B9E3A5A0A1E0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=D:\TDitbam-Streamer-Suite\installer
OutputBaseFilename=TDitbam-Streamer-Suite-Setup-v3.3.0
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\TDitbam-Streamer-Suite\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
