<<<<<<< HEAD
#define MyAppName "TDitbam Streamer Suite"
#define MyAppVersion "3.3.0 (fix)"
=======
; Script generated by the Gemini CLI for TDitbam Streamer Suite
#define MyAppName "Streamer Suite"
#define MyAppVersion "3.5.0"
>>>>>>> 7ab37d65cc4e2d9b863564c0744c6ef694c867bb
#define MyAppPublisher "Tditbam"
#define MyAppURL "https://github.com/TDitbam/TDitbam-Streamer-Suite"
#define MyAppExeName "StreamerSuite.exe"

[Setup]
AppId={{D3D3A6A0-9E1D-4F1B-9D8F-B9E3A5A0A1E0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
<<<<<<< HEAD
OutputDir=installer
OutputBaseFilename=TDitbam-Streamer-Suite-Setup-v3.3.0-fix
=======
OutputDir=D:\TDitbam-Streamer-Suite\installer
OutputBaseFilename=StreamerSuite-Setup-v3.5.0
>>>>>>> 7ab37d65cc4e2d9b863564c0744c6ef694c867bb
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
<<<<<<< HEAD
Source: "dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "config.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "resources\*"; DestDir: "{app}\resources"; Flags: ignoreversion recursesubdirs createallsubdirs
=======
; หลักฐานการรัน (ใช้ชื่อตามที่ระบุใน .spec)
Source: "D:\TDitbam-Streamer-Suite\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; ไฟล์ตั้งค่าเบื้องต้น
Source: "D:\TDitbam-Streamer-Suite\config.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\TDitbam-Streamer-Suite\bad_words.txt"; DestDir: "{app}"; Flags: ignoreversion
; ทรัพยากรอื่นๆ
Source: "D:\TDitbam-Streamer-Suite\resources\*"; DestDir: "{app}\resources"; Flags: ignoreversion recursesubdirs createallsubdirs
>>>>>>> 7ab37d65cc4e2d9b863564c0744c6ef694c867bb

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

<<<<<<< HEAD
[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
=======


[Dirs]
Name: "{app}\logs"
Name: "{app}\msg_queue"
Name: "{app}\temp_audio"
>>>>>>> 7ab37d65cc4e2d9b863564c0744c6ef694c867bb
