; Script generated by the Gemini CLI for TDitbam Streamer Suite
#define MyAppName "TDitbam Streamer Suite"
#define MyAppVersion "3.4.0"
#define MyAppPublisher "Tditbam"
#define MyAppURL "https://github.com/TDitbam/TDitbam-Streamer-Suite"
#define MyAppExeName "main.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{D3D3A6A0-9E1D-4F1B-9D8F-B9E3A5A0A1E0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputDir=D:\TDitbam-Streamer-Suite\installer
OutputBaseFilename=TDitbam-Streamer-Suite-Setup-v3.4.0
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; หลักฐานการรัน (ถ้าใช้ PyInstaller รวมเป็นไฟล์เดียว)
Source: "D:\TDitbam-Streamer-Suite\dist\main.exe"; DestDir: "{app}"; Flags: ignoreversion
; ไฟล์ตั้งค่าเบื้องต้น
Source: "D:\TDitbam-Streamer-Suite\config.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\TDitbam-Streamer-Suite\bad_words.txt"; DestDir: "{app}"; Flags: ignoreversion
; ทรัพยากรอื่นๆ
Source: "D:\TDitbam-Streamer-Suite\resources\*"; DestDir: "{app}\resources"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Dirs]
Name: "{app}\logs"
Name: "{app}\msg_queue"
Name: "{app}\temp_audio"
